// <auto-generated />
namespace WebBanSach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class sync_model_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sync_model_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "202504131421548_sync_model_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
